### ISSUE TITLE
Zeebe with simple monitor in different namespaces

### ISSUE THREAD

**Issue by phoenixwp** [zeebe-io/zeebe-hazelcast-exporter#25] opened 2020-02-03 19:30 UTC
Hello, guys

I'm trying to deploy two different Zeebe clusters in two different namespaces in Kubernetes, let's say dev and qa.
I made my own docker image with Zeebe-hazelcast-exporter included in it.
I deploy both clusters with following versions: Zeebe 0.21.1, monitor 0.16.0, Hazelcast-exporter  0.6.0. All is great. Simple monitor connects to Hazelcast and fetches data from it.

When I try to upgrade dev cluster to latest versions (Zeebe 0.22.1, monitor 0.17.0, Hazelcast-exporter  0.7.0) the problem appears. Old cluster (in qa namespaces) shows me the following error:

> 2020-02-03 19:19:18.150 [exporter] [zeebe-0.zeebe.uat.svc.cluster.local:26501-zb-fs-workers-0] INFO  com.hazelcast.core.LifecycleService - [10.44.0.37]:5701 [dev] [3.11] [10.44.0.37]:5701 is STARTING
2020-02-03 19:19:18.320 [exporter] [zeebe-0.zeebe.uat.svc.cluster.local:26501-zb-fs-workers-0] INFO  com.hazelcast.internal.cluster.impl.MulticastJoiner - [10.44.0.37]:5701 [dev] [3.11] Trying to join to discovered node: **[10.44.0.22]:5702**
2020-02-03 19:19:18.343 [] [hz._hzInstance_1_dev.cached.thread-3] INFO  com.hazelcast.nio.tcp.TcpIpConnector - [10.44.0.37]:5701 [dev] [3.11] Connecting to /10.44.0.22:5702, timeout: 0, bind-any: true
2020-02-03 19:19:18.349 [] [hz._hzInstance_1_dev.IO.thread-in-0] INFO  com.hazelcast.nio.tcp.TcpIpConnection - [10.44.0.37]:5701 [dev] [3.11] Initialized new cluster connection between /10.44.0.37:46791 and /10.44.0.22:5702
2020-02-03 19:19:18.351 [] [hz._hzInstance_1_dev.IO.thread-in-0] ERROR com.hazelcast.spi.NodeEngine - [10.44.0.37]:5701 [dev] [3.11] Header flags [100001] specify an undefined packet type UNDEFINED5
2020-02-03 19:19:19.346 [] [hz._hzInstance_1_dev.priority-generic-operation.thread-0] ERROR com.hazelcast.security - [10.44.0.37]:5701 [dev] [3.11] Node could not join cluster. Before join check failed node is going to shutdown now!
2020-02-03 19:19:19.347 [] [hz._hzInstance_1_dev.priority-generic-operation.thread-0] ERROR com.hazelcast.security - [10.44.0.37]:5701 [dev] [3.11] Reason of failure for node join: Joining node's version 3.11.0 is not compatible with cluster version 3.12 (Rolling Member Upgrades are only supported for the next minor version) (Rolling Member Upgrades are only supported in Hazelcast Enterprise)
2020-02-03 19:19:19.347 [] [hz._hzInstance_1_dev.priority-generic-operation.thread-0] WARN  com.hazelcast.instance.Node - [10.44.0.37]:5701 [dev] [3.11] Terminating forcefully...
2020-02-03 19:19:19.347 [] [hz._hzInstance_1_dev.priority-generic-operation.thread-0] INFO  com.hazelcast.instance.Node - [10.44.0.37]:5701 [dev] [3.11] Shutting down multicast service...

Obviously new Hazelcast tries to join into another cluster in qa namespace(market with bold), but I don’t need it to do that.

Is there any way to configure Hazelcast with another group or cluster name to separate two different clusters?

Thanks in advance

**Comment by saig0** [comment] 2020-02-06 07:28
Hi @phoenixwp, 

I transferred this issue into the Hazelcast exporter repository since it is mainly about the exporter :)

In Hazelcast, it is possible to define cluster groups. Each group is separated and acts independently. See https://docs.hazelcast.org/docs/3.12.6/manual/html-single/index.html#creating-cluster-groups.

However, it sounds weird that two different Zeebe clusters in different K8s namespaces share one Hazelcast cluster. I would assume that both clusters have their own Hazelcast instance/cluster.

**Comment by salaboy** [comment] 2020-02-07 15:56
@saig0 @phoenixwp I think that this will be a super common requirement. In my opinion, the exporter should also add the cluster name to the exported information, so the same Hazelcast cluster can be used by multiple zeebe clusters. 

@phoenixwp I am assuming that you are writing your own deployment descriptors for simple monitor, are you willing to contribute with those, so we can also have a Helm Chart for Simple Monitor components?

**Comment by phoenixwp** [comment] 2020-02-07 16:51
Hi @saig0,
I agree  it looks a little bit strange, but logs above show exactly that behaviour. 

> exporter should also add the cluster name to the exported information, so the same Hazelcast cluster can be used by multiple zeebe clusters

I suppose, in this case Zeebe monitor will show the information from all Zeebe clusters in different environments. Isn't it? It could be hard to determine for developers, which workflow belongs to which environment(e.g. dev, qa, staging). Am I right?

Is it possible, to set Hazelcast group name in [exporters] section in zeebe.cfg.toml?

@salaboy,
yep, that's correct. I made my own Zeebe docker container with Hazelcast exporter included on it.
Also I described deployment, ingress and service specs for K8s and included them into Zeebe cluster Helm chart.
I can share the specs with the project, how would you like to get it? PR to Zeebe-helm?

**Comment by salaboy** [comment] 2020-02-07 17:08
@phoenixwp what we can do is to add your manifest for simple monitor in an issue and I can create the chart when we understand how many new components you are creating. 
I've opened an issue in github.com/zeebe-cluster-helm about the Hazelcast exporter.. I think that we can mount it, instead of recreating the docker image. Help on that front will be also appreciated.

**Comment by phoenixwp** [comment] 2020-02-07 18:11
@salaboy ok, I will post my manifests here later

**Comment by phoenixwp** [comment] 2020-02-10 19:43
So, here are my manifests for Zeebe monitor
**monitor-deployment.yaml:**

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.global.zeebe }}-monitor
  labels:
    app.kubernetes.io/name: {{ include "zeebe-cluster.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app: {{ .Values.global.zeebe }}-monitor
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "zeebe-cluster.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
      app: {{ .Values.global.zeebe }}-monitor
  serviceName: {{ tpl .Values.global.zeebe . | quote }}
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "zeebe-cluster.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        app: "{{ .Values.global.zeebe }}-monitor"
    spec:
      containers:
      - name: "{{ .Values.global.zeebe }}-monitor"
        image: "{{ .Values.monitor.image.repository }}:{{ .Values.monitor.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        command: ["java", "-jar", "/usr/local/zeebe-simple-monitor.jar", "--io.zeebe.monitor.connectionString={{ .Values.global.zeebe }}:{{ .Values.service.gateway.port }}", "--io.zeebe.monitor.hazelcast.connection={{ .Values.global.zeebe }}:{{ .Values.service.hazelcast.port }}"]
        ports:
        - containerPort: 8080
          name: http
```

**monitor-service.yaml:**
```
apiVersion: v1
kind: Service
metadata:
  name: "{{ .Values.global.zeebe }}-monitor"
  labels:
    app.kubernetes.io/name: {{ include "zeebe-cluster.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app: "{{ .Values.global.zeebe }}-monitor"
spec:
  clusterIP: None
  publishNotReadyAddresses: true
  type: {{ .Values.service.type }}
  ports:
    - port: 8080
      protocol: TCP
      name: http-monitor
  selector:
    app.kubernetes.io/name: {{ include "zeebe-cluster.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app: "{{ .Values.global.zeebe }}-monitor"
```

**monitor-ingress.yaml:**
```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: "{{ .Values.global.zeebe }}-monitor"
  labels:
    app.kubernetes.io/name: {{ include "zeebe-cluster.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app: "{{ .Values.global.zeebe }}-monitor"
spec:
  rules:
  - host: "{{ .Values.monitor.ingress.host }}"
    http:
      paths:
      - backend:
          serviceName: "{{ .Values.global.zeebe }}-monitor"
          servicePort: 8080
        path: "{{ .Values.monitor.ingress.path }}"
```

part of **values.yaml**:
```
global:
  elasticsearch:
    host: "elasticsearch"
    port: 9200
  zeebe: "{{ .Release.Name }}-zeebe"

service:
  type: ClusterIP
  hazelcast:
    port: 5701
  http:
    port: 9600
  gateway:
    port: 26500
  command:
    port: 26501
  internal:
    port: 26502

monitor:
  image:
    repository: camunda/zeebe-simple-monitor
    tag: 0.16.0

  ingress:
    enabled: true
    annotations: {}
    path: "/"
    host: "zeebe"
```

Also Dockerfile with Hazelcast exporter:
```
FROM camunda/zeebe:0.22.1
USER root
RUN  wget -O /usr/local/zeebe/lib/zeebe-hazelcast-exporter.jar https://github.com/zeebe-io/zeebe-hazelcast-exporter/releases/download/0.7.0/zeebe-hazelcast-exporter-0.7.0-jar-with-dependencies.jar
```

**Comment by salaboy** [comment] 2020-02-12 20:16
@phoenixwp I think that next week I can get a helm chart for it with your provided templates.. 
The only missing part will be the hazelcast exporter.. we need to find a way to mount that file using a volume mount into the docker image that doesn't have the exporter in it.

**Comment by salaboy** [comment] 2020-02-17 14:20
@phoenixwp this is still on my todo list.. I haven't forgot about it.. just other stuff got in the middle.

**Comment by phoenixwp** [comment] 2020-02-18 09:36
@salaboy no worries :)

Why don't you want to put the exporter inside Docker image?

Another question - is there any way to configure Hazelcast exporter with <group name> parameter?

**Comment by salaboy** [comment] 2020-02-18 09:38
@phoenixwp baking another docker image is painful and we don't want to add a bunch of exporters that will be disabled by default. I would rather add the jar to the classpath + configurations on-demand, but unfortunately, I haven't had the time to experiment with it.

**Comment by saig0** [comment] 2020-02-18 09:39
> Another question - is there any way to configure Hazelcast exporter with parameter?

All configuration options are listed here: https://github.com/zeebe-io/zeebe-hazelcast-exporter#configuration

Feel free to open an issue (or a PR) if you need more.

**Comment by pocorschi** [comment] 2020-04-25 09:31
- deployed hazelcast standalone chart
- deployed zeebe-cluster helm with new 0.9.0-alpha1 hazelcast exporter pointing to the external hazelcast
- deployed a sample workflow on zeebe
- ran zeeqs locally pointing to the external hazecast cluster
- all good so far :)

Notes:

- I had to manually delete the z-cluster pods to force them to start properly (replicated this two times) I dont know where the issue is.
- exporter doesnt seem to want to connect if hazelcast version is 4.0 (the helm chart is using 4.0) so i downgraded it to the one used in docker compose by @saig0  which is 3.16.2

@salaboy - you mentioned working on a ZeeQS helm chart. Is there an ETA on that or should I go ahead and try my hand at one?

<img width="1337" alt="Screenshot 2020-04-25 at 12 28 17" src="https://user-images.githubusercontent.com/233198/80276264-40767700-86f0-11ea-83e7-3282042bd12b.png">

**Closed** 2020-08-19 04:47 UTC
